package main

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// realResourcesSrcDir/realDocsDir are this test's paths to the real resources/ source tree and
// its committed docs/resources/ output, relative to this package's own directory
// (tools/generate-docs/) -- two levels up to the repository root.
const (
	realResourcesSrcDir = "../../resources"
	realDocsDir         = "../../docs/resources"
)

// indexMarkdownFile is docs/resources/index.md -- the generated resource-type index. It lives in
// the same directory as the per-type pages but is not one of them.
const indexMarkdownFile = "index.md"

// docPropertyKeyLine matches renderDoc's own `- `key`\n` list-item format exactly (see
// renderDoc's "## Properties" block above), so this test's expectation is parsed from the
// committed doc using the identical shape renderDoc writes, never a looser regex that could
// accidentally match unrelated Markdown.
var docPropertyKeyLine = regexp.MustCompile("^- `([^`]+)`$")

// TestPropertyKeys_MatchCommittedDocs_AllRegisteredTypes closes the wider half of
// 04-VERIFICATION.md's Gap 1 (Properties() test coverage) WITHOUT hand-writing an exact-key-set
// test into all ~34 remaining resources/*_test.go files. docs/resources/generated_test.go's own
// TestGeneratedDocs_SpotCheckPropertyKeys hand-maintains an expected key list for only 5 of the 37
// registered types; a Properties() key silently added, renamed, or removed in any of the OTHER 32
// types would fail no test at all as long as nobody happened to re-run
// `go run ./tools/generate-docs` afterward -- the doc would simply go stale and silently keep
// documenting a key the type no longer actually sets (or omit one it newly does).
//
// This test re-derives each registered type's expected key set FRESH, every run, straight from
// its real resources/<snake_case>.go source -- via the exact same go/ast extraction
// (extractPropertyKeys / propertyKeysForType / loadPropertyConstants) run() uses to write
// docs/resources/<Type>.md in the first place -- and diffs it against what is actually committed
// in docs/resources/<Type>.md, for EVERY registered type, not only 5. A key silently disappearing
// (or a stale, un-regenerated doc) fails this single test immediately, naming exactly which
// type(s) it happened to, rather than requiring a hand-typed exact-key assertion to have been
// added to that type's own test file in advance.
//
// See CONTRIBUTING.md section 6 for why this is the accepted mechanism satisfying "every
// registered resource type has a Properties() test asserting its exact property keys" (ROADMAP
// Phase 4 Success Criterion 4) for the wave at large, rather than 34 more hand-written per-type
// tests -- RouteTable and SecurityList (resources/route_table_test.go,
// resources/security_list_test.go) additionally get dedicated, hand-written exact-key-set tests,
// since 04-VERIFICATION.md found those two had zero Properties() assertions of any kind, a
// stronger gap than "spot-checked but not exhaustively."
//
// The registered-type-name list is read from docs/resources/*.md's own filenames (already proven
// to equal registry.GetNames() by docs/resources/generated_test.go's own
// TestGeneratedDocsCoverage_MatchesRegisteredTypeCount, run in a SEPARATE test binary/process --
// docs/resources is its own package) rather than calling registry.GetNames() directly here --
// this package's OTHER tests in main_test.go call registry.ClearRegistry() and never restore the
// real, blank-imported registrations afterward (they only ever need synthetic fixture types), so
// reading real registered names via registry.* from this same test binary would be a test-order
// hazard this test has no need to introduce. Reading the doc directory listing carries no such
// risk.
func TestPropertyKeys_MatchCommittedDocs_AllRegisteredTypes(t *testing.T) {
	entries, err := os.ReadDir(realDocsDir)
	if err != nil {
		t.Fatalf("reading %s: %v", realDocsDir, err)
	}

	constants, err := loadPropertyConstants(realResourcesSrcDir)
	if err != nil {
		t.Fatalf("loadPropertyConstants(%s): %v", realResourcesSrcDir, err)
	}

	checked := 0
	for _, entry := range entries {
		name := entry.Name()
		// indexFileName is generated by the same tool but is a page, not a type -- it must not
		// be read as one.
		if entry.IsDir() || !strings.HasSuffix(name, ".md") || name == indexMarkdownFile {
			continue
		}
		typeName := strings.TrimSuffix(name, ".md")

		want := docCommittedPropertyKeys(t, filepath.Join(realDocsDir, name))
		got, err := propertyKeysForType(realResourcesSrcDir, typeName, constants)
		if err != nil {
			t.Errorf("%s: propertyKeysForType: %v", typeName, err)
			continue
		}

		sort.Strings(want)
		sort.Strings(got)
		if strings.Join(got, ",") != strings.Join(want, ",") {
			t.Errorf(
				"%s: Properties() keys extracted fresh from resources/%s.go = %v, but committed "+
					"docs/resources/%s.md documents %v -- run `go run ./tools/generate-docs` and "+
					"commit the result",
				typeName, toSnakeCase(typeName), got, typeName, want,
			)
		}
		checked++
	}

	if checked == 0 {
		t.Fatal("no docs/resources/*.md files found -- test setup is broken")
	}
}

// docCommittedPropertyKeys parses path's "## Properties" list-item lines (renderDoc's own
// `- `key`\n` format) and returns the unsorted key list found.
func docCommittedPropertyKeys(t *testing.T, path string) []string {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	var keys []string
	for _, line := range strings.Split(string(content), "\n") {
		if m := docPropertyKeyLine.FindStringSubmatch(line); m != nil {
			keys = append(keys, m[1])
		}
	}
	return keys
}
