// Package docs_test proves tools/generate-docs' output (DOC-04), committed under docs/resources/,
// covers every registered resource type -- run for the first time against the real,
// fully-populated resources package, not the fixture-based unit tests already covering
// tools/generate-docs/main.go's extraction logic in isolation.
package docs_test

import (
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/ekristen/libnuke/pkg/registry"

	// Blank-imported so registry.GetNames() reflects every real registered type -- the same
	// requirement resources_test/registration_test.go and resources_test/filter_contract_test.go
	// already establish for this wave's other structural checks.
	_ "github.com/naviteq/oci-nuke/resources"
)

// indexMarkdownFile is docs/resources/index.md -- the generated resource-type index. It lives in
// the same directory as the per-type pages but is not one of them.
const indexMarkdownFile = "index.md"

// TestGeneratedDocsCoverage_MatchesRegisteredTypeCount is DOC-04's coverage guarantee stated as
// its own named criterion: the exact set of docs/resources/<Type>.md files present on disk must
// equal the exact set of names registry.GetNames() returns -- not merely a non-zero file count,
// and not merely a matching count that could hide a name mismatch (e.g. a stale doc left behind
// for a type that was since renamed or removed, while a genuinely new type's doc silently never
// got generated).
func TestGeneratedDocsCoverage_MatchesRegisteredTypeCount(t *testing.T) {
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("reading docs/resources/: %v", err)
	}

	gotNames := make(map[string]bool)
	for _, entry := range entries {
		name := entry.Name()
		// indexFileName is generated by the same tool but is a page, not a type -- it must not
		// be read as one.
		if entry.IsDir() || !strings.HasSuffix(name, ".md") || name == indexMarkdownFile {
			continue
		}
		gotNames[strings.TrimSuffix(name, ".md")] = true
	}

	wantNames := make(map[string]bool)
	for _, name := range registry.GetNames() {
		wantNames[name] = true
	}

	var missingDocs, staleDocs []string
	for name := range wantNames {
		if !gotNames[name] {
			missingDocs = append(missingDocs, name)
		}
	}
	for name := range gotNames {
		if !wantNames[name] {
			staleDocs = append(staleDocs, name)
		}
	}
	sort.Strings(missingDocs)
	sort.Strings(staleDocs)

	if len(missingDocs) > 0 {
		t.Errorf(
			"registered resource type(s) with no generated doc: %s -- re-run `go run "+
				"./tools/generate-docs` and commit its output under docs/resources/",
			strings.Join(missingDocs, ", "),
		)
	}
	if len(staleDocs) > 0 {
		t.Errorf(
			"docs/resources/*.md file(s) with no corresponding registered type: %s -- these are "+
				"stale (the type was renamed or removed); delete the stale .md file(s) and re-run "+
				"`go run ./tools/generate-docs`",
			strings.Join(staleDocs, ", "),
		)
	}

	if len(gotNames) != len(wantNames) {
		t.Errorf(
			"docs/resources/ contains %d .md file(s), registry.GetNames() returns %d name(s) -- "+
				"counts must match exactly (DOC-04)",
			len(gotNames), len(wantNames),
		)
	}
}

// Property key constants shared by baseProperties across nearly every spot-checked type below --
// declared once here so none of these raw string literals repeats 3+ times in this file (goconst),
// mirroring resources/support.go's own reason for declaring the same constants in that package.
const (
	keyID                 = "id"
	keyName               = "name"
	keyCompartmentID      = "compartment_id"
	keyLifecycleState     = "lifecycle_state"
	keyTimeCreated        = "time_created"
	keyAvailabilityDomain = "availability_domain"
)

// spotCheckPropertyKeys hardcodes each spot-checked type's expected documented property keys,
// sourced directly from that type's own resources/*_test.go Properties() assertions (Plans
// 04-04/04-06/04-08/04-09/04-10) -- not re-derived here -- so this test proves the AST extraction
// in tools/generate-docs/main.go works across every domain plan in this wave, not only the
// fixture Plan 04-03's own unit test used. Bucket's set is notably short: unlike the other four,
// Bucket.Properties() does not delegate to the shared baseProperties helper (it has no
// LifecycleState or TimeCreated field, per 04-RESEARCH.md Q4), so it documents only name,
// compartment_id, and namespace.
//
// This hand-maintained map only covers 5 of 37 registered types. Exact-key-set correctness for
// every OTHER registered type is proven separately, without a hand-maintained list, by
// tools/generate-docs/freshness_test.go's TestPropertyKeys_MatchCommittedDocs_AllRegisteredTypes
// -- see CONTRIBUTING.md section 6's "Properties() exact-key-set correctness" for why that shared
// test, not 32 more entries here or in per-type _test.go files, is this project's accepted
// mechanism for ROADMAP.md Phase 4 Success Criterion 4.
var spotCheckPropertyKeys = map[string][]string{
	"Instance": {
		keyAvailabilityDomain, keyCompartmentID, keyID, keyLifecycleState, keyName, "shape", keyTimeCreated,
	},
	"Vcn": {
		"cidr_block", keyCompartmentID, "default_route_table_id", "default_security_list_id",
		keyID, keyLifecycleState, keyName, keyTimeCreated,
	},
	"Bucket": {keyCompartmentID, keyName, "namespace"},
	"LoadBalancer": {
		"backend_sets", "certificates", keyCompartmentID, keyID, keyLifecycleState, keyName, keyTimeCreated,
	},
	"MountTarget": {
		keyAvailabilityDomain, keyCompartmentID, "export_set_id", keyID, keyLifecycleState, keyName, keyTimeCreated,
	},
}

// TestGeneratedDocs_SpotCheckPropertyKeys opens each spot-checked type's generated doc and proves
// it contains every one of that type's known property keys, rendered exactly as renderDoc
// (tools/generate-docs/main.go) writes them: a Markdown list item, `- \`key\`\n`.
func TestGeneratedDocs_SpotCheckPropertyKeys(t *testing.T) {
	names := make([]string, 0, len(spotCheckPropertyKeys))
	for name := range spotCheckPropertyKeys {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		keys := spotCheckPropertyKeys[name]
		content, err := os.ReadFile(name + ".md")
		if err != nil {
			t.Errorf("reading %s.md: %v", name, err)
			continue
		}
		for _, key := range keys {
			want := "- `" + key + "`"
			if !strings.Contains(string(content), want) {
				t.Errorf("%s.md missing documented property key %q (want to contain %q)", name, key, want)
			}
		}
	}
}

// spotCheckDependsOn hardcodes the known DependsOn list for four types spanning multiple domain
// plans, proving `oci-nuke resource-types`' DependsOn column (pkg/commands/list/list.go, which
// reads the identical registry.Registration.DependsOn field this test reads directly) reflects
// real dependency declarations, not only the synthetic fixture
// pkg/commands/list/list_test.go's own formatting test uses.
var spotCheckDependsOn = map[string][]string{
	"Vcn": {
		"DhcpOptions", "DrgAttachment", "InternetGateway", "LocalPeeringGateway", "NatGateway",
		"NetworkSecurityGroup", "RouteTable", "SecurityList", "ServiceGateway", "Subnet",
	},
	"Drg":        {"DrgAttachment"},
	"Bucket":     {"MultipartUpload", "ObjectVersion", "PreauthenticatedRequest", "ReplicationPolicy", "RetentionRule"},
	"FileSystem": {"Export", "Snapshot"},
}

// TestResourceTypes_DependsOnSpotCheck proves registry.GetRegistration(name).DependsOn --
// pkg/commands/list/list.go's `resource-types` command prints this exact field, unmodified, in
// its DependsOn column -- is non-empty and correct for four types spanning three domain plans
// (Plans 04-05/04-06/04-04/04-08).
func TestResourceTypes_DependsOnSpotCheck(t *testing.T) {
	names := make([]string, 0, len(spotCheckDependsOn))
	for name := range spotCheckDependsOn {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		want := append([]string(nil), spotCheckDependsOn[name]...)
		sort.Strings(want)

		reg := registry.GetRegistration(name)
		if reg == nil {
			t.Errorf("registry.GetRegistration(%q) = nil, want a registration", name)
			continue
		}

		got := append([]string(nil), reg.DependsOn...)
		sort.Strings(got)

		if strings.Join(got, ",") != strings.Join(want, ",") {
			t.Errorf("%s DependsOn = %v, want %v", name, got, want)
		}
	}
}

// indexRow matches renderIndex's own table-row format exactly: `| [Name](Name.md) | notes |`.
var indexRow = regexp.MustCompile(`^\| \[([^\]]+)\]\(([^)]+)\) \|`)

// TestGeneratedIndex_ListsEveryRegisteredType gives index.md the guarantee the per-type pages
// already have. The two tests above skip index.md by name -- necessarily, since it is a page and
// not a type -- and an exclusion with nothing behind it is how a generated file quietly goes
// stale. So the index is checked here on its own terms: every registered type appears exactly
// once, nothing appears that is not registered, and each row's link resolves to a file that
// exists (a correct name pointing at a missing page is still a broken index).
func TestGeneratedIndex_ListsEveryRegisteredType(t *testing.T) {
	content, err := os.ReadFile(indexMarkdownFile)
	if err != nil {
		t.Fatalf("reading %s: %v", indexMarkdownFile, err)
	}

	siblings, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("reading docs/resources/: %v", err)
	}
	present := make(map[string]bool, len(siblings))
	for _, entry := range siblings {
		if !entry.IsDir() {
			present[entry.Name()] = true
		}
	}

	listed := make(map[string]int)
	for _, line := range strings.Split(string(content), "\n") {
		m := indexRow.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		listed[m[1]]++

		// Resolved against a listing of this directory rather than by stat'ing the link
		// text: the target has to be a plain sibling filename, and looking it up in a set
		// says exactly that without handing a value parsed out of a Markdown file to the
		// file system.
		if !present[m[2]] {
			t.Errorf("%s: row for %s links to %q, which is not a file in this directory", indexMarkdownFile, m[1], m[2])
		}
	}

	registered := make(map[string]bool)
	for _, name := range registry.GetNames() {
		registered[name] = true
	}

	for name := range registered {
		switch listed[name] {
		case 1:
		case 0:
			t.Errorf("%s: registered type %s is missing -- re-run `go run ./tools/generate-docs`", indexMarkdownFile, name)
		default:
			t.Errorf("%s: registered type %s is listed %d times", indexMarkdownFile, name, listed[name])
		}
	}
	for name := range listed {
		if !registered[name] {
			t.Errorf("%s: lists %s, which is not a registered type", indexMarkdownFile, name)
		}
	}

	if len(listed) != len(registered) {
		t.Errorf("%s lists %d type(s), registry.GetNames() returns %d", indexMarkdownFile, len(listed), len(registered))
	}
}
